import { auth, currentUser } from '@clerk/nextjs/server'
import { redirect } from 'next/navigation'
import Link from 'next/link'
import { unstable_cache } from 'next/cache'
import { prisma } from '@/lib/db'
import DashboardActions from './DashboardActions'

export const metadata = {
  title: "Dashboard — Career Navigator",
  description:
    "View your career assessment results, skill gap analysis, and personalised career paths in one place.",
  robots: { index: false, follow: false },
  alternates: {
    canonical: `${process.env.NEXT_PUBLIC_APP_URL}/dashboard`,
  },
  openGraph: {
    images: [`${process.env.NEXT_PUBLIC_APP_URL}/api/og?title=Your+Career+Dashboard&description=AI-powered+career+paths%2C+skill+gaps%2C+and+job+matches+in+one+place`],
  },
};

export default async function DashboardPage() {
  const { userId } = await auth()
  if (!userId) redirect('/sign-in')

  // Dashboard is accessible without an assessment — empty state CTAs guide new users
  // Onboarding is opt-in via the welcome CTA, not a forced redirect (prevents skip loop)

  const user = await currentUser()

  // T050: Cached DB queries — revalidate hourly, tagged per user for on-demand purge
  const getDashboardData = unstable_cache(
    async (uid) => Promise.all([
      prisma.career_assessments.findFirst({ where: { clerkId: uid, isArchived: false } }),
      prisma.career_guidance.findFirst({ where: { clerkId: uid }, orderBy: { generatedAt: 'desc' } }),
      prisma.skill_gaps.findFirst({ where: { clerkId: uid }, orderBy: { createdAt: 'desc' } })
    ]),
    ['dashboard'],
    { revalidate: 3600, tags: ['dashboard', `dashboard-${userId}`] }
  )
  const [rawAssessment, rawGuidance, rawSkillGap] = await getDashboardData(userId)

  const assessment = rawAssessment ? {
    mbtiType: rawAssessment.personality?.type ?? null,
    iqScore: rawAssessment.iq?.iq_score ?? null,
    qualification: rawAssessment.qualification,
    skills: rawAssessment.skills
  } : null

  const guidance = rawGuidance ? {
    topCareers: (rawGuidance.recommendations ?? [])
      .slice(0, 3)
      .map(c => ({ title: c.title, matchScore: c.matchScore, marketOutlook: c.marketOutlook })),
    overallTimeline: rawGuidance.overallTimeline,
    generatedAt: rawGuidance.generatedAt
  } : null

  const skillGap = rawSkillGap ? {
    compatibilityScore: rawSkillGap.analysis?.compatibilityScore ?? null,
    missingSkills: (rawSkillGap.analysis?.missingSkills ?? []).slice(0, 5),
    matchingSkills: rawSkillGap.analysis?.matchingSkills ?? [],
    analyzedAt: rawSkillGap.createdAt
  } : null

  // Nudge card state (FR-021, FR-022, FR-023)
  const hasAssessment = rawAssessment !== null
  const hasSkillGap = rawSkillGap !== null
  const showNudge = hasAssessment !== hasSkillGap // XOR
  const nudgeTarget = hasAssessment ? 'skillgap' : 'assessment'

  const courses = rawSkillGap?.resources?.courses?.slice(0, 4) ?? []

  // T035: Job listings — direct DB query (constitution §Dashboard: server-side, not client-side fetch)
  // Uses job_cache table; stale/missing cache shows friendly message (Adzuna fetch via /api/jobs on demand)
  let jobListings = []
  let jobsMessage = null
  const CACHE_TTL_MS = 6 * 60 * 60 * 1000
  try {
    const topCareer = (rawGuidance?.recommendations ?? [])[0]?.title ?? null
    if (topCareer) {
      const cachedJobs = await prisma.job_cache.findUnique({ where: { careerPathTitle: topCareer } })
      const isStale = !cachedJobs || (Date.now() - new Date(cachedJobs.fetchedAt).getTime()) > CACHE_TTL_MS
      if (cachedJobs) {
        jobListings = cachedJobs.listings ?? []
        if (isStale) jobsMessage = 'Showing cached results — refresh to update.'
      } else {
        jobsMessage = 'Job listings are loading. Check back in a moment.'
      }
    }
  } catch {
    jobsMessage = 'Job listings temporarily unavailable.'
  }

  return (
    <div className="min-h-screen pt-24 px-6 pb-10 md:px-10 bg-[#171717]">
      <div className="max-w-5xl mx-auto space-y-8">

        {/* Welcome banner for new users with no assessment */}
        {!assessment && (
          <div className="rounded-2xl p-6 bg-gradient-to-r from-[#1e3a8a]/30 to-[#3b82f6]/20 border border-blue-500/20 print:hidden">
            <h2 className="text-lg font-semibold text-white mb-1">Welcome to Career Navigator</h2>
            <p className="text-white/60 text-sm mb-4">Take the free AI-powered assessment to discover your best-fit career paths.</p>
            <Link href="/onboarding" className="inline-block px-5 py-2 rounded-lg text-sm font-medium text-white bg-gradient-to-r from-[#1e3a8a] to-[#3b82f6] hover:opacity-90 transition-opacity">
              Get Started →
            </Link>
          </div>
        )}

        {/* Print-only header */}
        <div className="hidden print:block mb-4">
          <h1 className="text-2xl font-bold text-black">Career Report — {user?.firstName ?? 'Student'}</h1>
          <p className="text-sm text-gray-500">Generated by Career Navigator · {new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}</p>
        </div>

        {/* Welcome banner */}
        <div className="print:hidden">
          <h1 className="text-3xl font-bold tracking-tight bg-gradient-to-r from-[#1e3a8a] to-[#60a5fa] bg-clip-text text-transparent">
            Welcome back, {user?.firstName ?? 'Student'}
          </h1>
          <p className="text-white/60 mt-1">Your career profile at a glance.</p>
        </div>

        {/* Nudge card — appears when only one of the two features is complete */}
        {showNudge && (
          <div className="rounded-2xl p-5 bg-gradient-to-r from-cyan-500/10 to-blue-500/10 border border-cyan-500/20 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 print:hidden">
            <div>
              <p className="text-white font-medium">
                {nudgeTarget === 'skillgap'
                  ? 'You have your career paths — now find your skill gaps'
                  : 'You have your skill gap report — now discover your career paths'}
              </p>
              <p className="text-white/50 text-sm mt-0.5">
                {nudgeTarget === 'skillgap'
                  ? 'Upload your resume to see exactly which skills you need for your top career match.'
                  : 'Complete the 10-minute assessment to get AI-powered career path recommendations.'}
              </p>
            </div>
            <Link
              href={nudgeTarget === 'skillgap' ? '/skillgapanalyzer' : '/careercounselling'}
              className="shrink-0 px-5 py-2 rounded-lg text-sm font-medium text-white bg-gradient-to-r from-cyan-500 to-blue-500 hover:opacity-90 transition-opacity whitespace-nowrap"
            >
              {nudgeTarget === 'skillgap' ? 'Scan Skill Gap →' : 'Start Assessment →'}
            </Link>
          </div>
        )}

        {/* Assessment Cards row */}
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
          {/* MBTI Card */}
          <div className="rounded-2xl p-6 bg-[#222222]">
            <p className="text-sm font-medium text-white/60 mb-2">MBTI Type</p>
            {assessment ? (
              <>
                <p className="text-2xl font-bold text-white">{assessment.mbtiType ?? '—'}</p>
                {assessment.mbtiType && (
                  <Link href={`/personalitytypes#${assessment.mbtiType}`}
                    className="text-xs text-blue-400 hover:underline mt-1 inline-block">
                    What does this mean?
                  </Link>
                )}
              </>
            ) : (
              // T032: Empty state CTA card
              <div className="space-y-2 mt-1">
                <p className="text-sm text-white/40">Take the assessment to discover your type</p>
                <Link href="/careercounselling"
                  className="inline-block text-xs font-medium text-blue-400 hover:text-blue-300 transition-colors">
                  Start Assessment →
                </Link>
              </div>
            )}
          </div>

          {/* IQ Card */}
          <div className="rounded-2xl p-6 bg-[#222222]">
            <p className="text-sm font-medium text-white/60 mb-2">IQ Score</p>
            {assessment ? (
              <p className="text-2xl font-bold text-white">{assessment.iqScore ?? '—'}</p>
            ) : (
              <div className="space-y-2 mt-1">
                <p className="text-sm text-white/40">Complete the IQ test during assessment</p>
                <Link href="/careercounselling"
                  className="inline-block text-xs font-medium text-blue-400 hover:text-blue-300 transition-colors">
                  Start Assessment →
                </Link>
              </div>
            )}
          </div>

          {/* Skill Match Card */}
          <div className="rounded-2xl p-6 bg-[#222222]">
            <p className="text-sm font-medium text-white/60 mb-2">Skill Match</p>
            {skillGap ? (
              <>
                <p className="text-2xl font-bold text-white">{skillGap.compatibilityScore}%</p>
                <div className="mt-2 h-2 rounded-full overflow-hidden bg-[#333333]">
                  <div
                    className="h-full rounded-full bg-gradient-to-r from-[#1e3a8a] to-[#60a5fa]"
                    style={{ width: `${skillGap.compatibilityScore}%` }}
                  />
                </div>
              </>
            ) : (
              <div className="space-y-2 mt-1">
                <p className="text-sm text-white/40">Upload your resume to get a match score</p>
                <Link href="/skillgapanalyzer"
                  className="inline-block text-xs font-medium text-blue-400 hover:text-blue-300 transition-colors">
                  Scan Skill Gap →
                </Link>
              </div>
            )}
          </div>
        </div>

        {/* Career Paths section */}
        <div className="rounded-2xl p-6 bg-[#222222]">
          <h2 className="text-xl font-semibold mb-4 bg-gradient-to-r from-[#1e3a8a] to-[#60a5fa] bg-clip-text text-transparent">
            Top Career Paths
          </h2>
          {!guidance ? (
            // T032: Illustrated empty state
            <div className="rounded-xl border border-white/10 bg-white/5 p-6 text-center space-y-3 print:hidden">
              <div className="text-3xl">🧭</div>
              <p className="text-white/70 font-medium">Discover your top 3 career matches</p>
              <p className="text-white/40 text-sm">Complete the career assessment to get AI-powered career path recommendations with match scores.</p>
              <Link href="/careercounselling"
                className="inline-block mt-2 px-4 py-2 rounded-lg text-sm font-medium text-white bg-gradient-to-r from-[#1e3a8a] to-[#3b82f6] hover:opacity-90 transition-opacity">
                Start Assessment →
              </Link>
            </div>
          ) : (
            <div className="space-y-5">
              {guidance.topCareers.map((career, i) => (
                <div key={i}>
                  <div className="flex items-center justify-between mb-1">
                    <span className="font-medium text-white">{career.title}</span>
                    <span className="text-sm text-white/60">{career.matchScore}% match</span>
                  </div>
                  <div className="h-2 rounded-full overflow-hidden bg-[#333333]">
                    <div
                      className="h-full rounded-full bg-gradient-to-r from-[#1e3a8a] to-[#60a5fa]"
                      style={{ width: `${career.matchScore}%` }}
                    />
                  </div>
                  <p className="text-xs text-white/60 mt-1">{career.marketOutlook}</p>
                </div>
              ))}
              <p className="text-xs text-white/60 pt-2">
                Generated {new Date(guidance.generatedAt).toLocaleDateString()}
              </p>
            </div>
          )}
        </div>

        {/* Skill Gap section */}
        <div className="rounded-2xl p-6 bg-[#222222]">
          <h2 className="text-xl font-semibold mb-4 bg-gradient-to-r from-[#1e3a8a] to-[#60a5fa] bg-clip-text text-transparent">
            Skill Gap Summary
          </h2>
          {!skillGap ? (
            <div className="rounded-xl border border-white/10 bg-white/5 p-6 text-center space-y-3 print:hidden">
              <div className="text-3xl">📊</div>
              <p className="text-white/70 font-medium">Find out exactly what skills you&apos;re missing</p>
              <p className="text-white/40 text-sm">Upload your resume and a job description to get a compatibility score and personalized learning roadmap.</p>
              <Link href="/skillgapanalyzer"
                className="inline-block mt-2 px-4 py-2 rounded-lg text-sm font-medium text-white bg-gradient-to-r from-[#1e3a8a] to-[#3b82f6] hover:opacity-90 transition-opacity">
                Run Skill Gap Scan →
              </Link>
            </div>
          ) : (
            <div className="space-y-4">
              <div>
                <p className="text-sm font-medium text-white mb-2">Missing Skills</p>
                <div className="flex flex-wrap gap-2">
                  {skillGap.missingSkills.map((skill, i) => (
                    <span key={i} className="px-3 py-1 rounded-full text-xs bg-[#4b1c1c] text-[#f87171]">{skill}</span>
                  ))}
                </div>
              </div>
              <div>
                <p className="text-sm font-medium text-white mb-2">Matching Skills</p>
                <div className="flex flex-wrap gap-2">
                  {skillGap.matchingSkills.map((skill, i) => (
                    <span key={i} className="px-3 py-1 rounded-full text-xs bg-[#1a3d2b] text-[#4ade80]">{skill}</span>
                  ))}
                </div>
              </div>
            </div>
          )}
        </div>

        {/* Courses panel — from latest skill gap resources */}
        {courses.length > 0 && (
          <div className="rounded-2xl p-6 bg-[#222222]">
            <h2 className="text-xl font-semibold mb-1 bg-gradient-to-r from-[#1e3a8a] to-[#60a5fa] bg-clip-text text-transparent">
              Recommended Courses
            </h2>
            <p className="text-white/40 text-xs mb-4">Based on your skill gap analysis</p>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              {courses.map((course, i) => (
                <a
                  key={i}
                  href={course.url}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="flex flex-col gap-1 p-4 rounded-xl bg-white/5 hover:bg-white/10 transition-colors border border-white/10 group"
                >
                  <div className="flex items-center justify-between gap-2">
                    <p className="font-medium text-white text-sm group-hover:text-blue-400 transition-colors line-clamp-1">{course.title}</p>
                    {course.isFree && (
                      <span className="text-[10px] font-semibold px-2 py-0.5 rounded-full bg-[#1a3d2b] text-[#4ade80] shrink-0">Free</span>
                    )}
                  </div>
                  <p className="text-white/40 text-xs">{course.platform}</p>
                </a>
              ))}
            </div>
            <Link href="/skillgapanalyzer" className="text-xs text-blue-400 hover:underline mt-3 inline-block print:hidden">
              Run new scan to refresh courses →
            </Link>
          </div>
        )}

        {/* T035: Job Listings panel — server-side fetched */}
        {guidance && (
          <div className="rounded-2xl p-6 bg-[#222222] print:hidden">
            <h2 className="text-xl font-semibold mb-4 bg-gradient-to-r from-[#1e3a8a] to-[#60a5fa] bg-clip-text text-transparent">
              Jobs Matching Your Top Career
            </h2>
            {jobListings.length > 0 ? (
              <div className="space-y-3">
                {jobListings.slice(0, 6).map((job, i) => (
                  <a
                    key={i}
                    href={job.url}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="flex items-start justify-between gap-4 p-4 rounded-xl bg-white/5 hover:bg-white/10 transition-colors border border-white/10 group"
                  >
                    <div className="min-w-0">
                      <p className="font-medium text-white text-sm group-hover:text-blue-400 transition-colors truncate">{job.title}</p>
                      <p className="text-white/50 text-xs mt-0.5">{job.company} · {job.location}</p>
                    </div>
                    {job.salary && (
                      <span className="text-xs text-white/40 shrink-0">{job.salary}</span>
                    )}
                  </a>
                ))}
              </div>
            ) : (
              <p className="text-white/40 text-sm">{jobsMessage ?? 'No job listings available right now. Check back later.'}</p>
            )}
          </div>
        )}

        {/* T036+T037: Download Report + Share Report buttons */}
        {guidance && <DashboardActions />}

        {/* Quick-action buttons */}
        <div className="flex flex-wrap gap-4 print:hidden">
          <Link href="/careercounselling"
            className="px-5 py-2 rounded-md text-sm font-medium text-white/80 hover:text-white transition-colors bg-[#222222]">
            Retake Assessment
          </Link>
          <Link href="/skillgapanalyzer"
            className="px-5 py-2 rounded-md text-sm font-medium text-white/80 hover:text-white transition-colors bg-[#222222]">
            New Skill Gap Scan
          </Link>
          <Link href="/personalitytypes"
            className="px-5 py-2 rounded-md text-sm font-medium text-white/80 hover:text-white transition-colors bg-[#222222]">
            View Personality Types
          </Link>
        </div>

      </div>
    </div>
  )
}
