import mongoose from 'mongoose';

// Schema for the individual analysis results generated by AI
const AnalysisResultSchema = new mongoose.Schema({
  missingSkills: [String],
  matchingSkills: [String],
  recommendations: String, // AI-generated advice in Markdown
  compatibilityScore: { type: Number, min: 0, max: 100 },
  suggestedRoadmap: [{
    step: String,
    resource: String // URL or Course name
  }]
});

const SkillGapSchema = new mongoose.Schema({
  // 1. Clerk & User Identification
  // We use clerkId as the primary link to the user
  clerkId: { type: String, required: true, index: true },
  name: { type: String, required: true }, // From your Personal Info
  age: { type: Number },

  // 2. Input Data
  // Storing the source of the resume for better UX tracking
  resumeSource: { 
    type: String, 
    enum: ['pdf', 'text'], 
    required: true 
  },
  
  // Storing resume in Markdown as requested
  resumeContent: { 
    type: String, 
    required: true 
  },
  
  // The specific job description the user is targeting
  jobDescription: { 
    type: String, 
    required: true 
  },

  // 3. AI Analysis Output
  // This stores the heavy processing results so you don't have to re-run AI calls
  analysis: AnalysisResultSchema,

  // 4. Metadata from Clerk / System
  metadata: {
    username: { type: String },
    createdAt: { type: Date, default: Date.now },
    clerkCreatedAt: { type: Number } // The 'createdAt' timestamp from Clerk backend
  }
}, { 
  collection: 'skillsgap', 
  timestamps: true 
});

// For Next.js: Prevents model re-creation during hot-reloads
const SkillGap = mongoose.models.SkillGap || mongoose.model('SkillGap', SkillGapSchema);

export default SkillGap;